#!/bin/bash
set -euo pipefail

PASSAGE=$HOME/.local/bin/passage
PREFIX=${PASSAGE_DIR:-$HOME/.passage/store}

name=$(
	cd "$PREFIX"
	find . -type f -name '*.age' -exec sh -c '
		for f; do
			f=${f#./}
			echo "${f%.age}"
		done
	' sh-find {} + | wmenu -i -l 10 -p "Passage:" "$@"
)

entry=$($PASSAGE show "$name")

key=$(
	{
		echo "Password"
		tail -n +2 <<<"$entry" | while IFS=: read -r key _; do
			case $key in
			"") break ;;
			"otpauth") echo 'OTP' ;;
			*) echo "$key" ;;
			esac
		done
	} | wmenu -i -l 10 -p "Passage:" "$@"
)

case $key in
"Password") value=$(head -n1 <<<"$entry") ;;
"OTP") value=$($PASSAGE otp "$name") ;;
*) value=$(sed -n "s/^$key: *//p" <<<"$entry") ;;
esac

echo -n "$value" | wtype -
