#!/bin/bash
set -euo pipefail

PASSAGE=$HOME/.local/bin/passage
PREFIX=${PASSAGE_DIR:-$HOME/.passage/store}

name=$(
	cd "$PREFIX"
	find . -type f -name '*.age' -exec sh -c '
		for f; do
			f=${f#./}
			printf "%s\n" "${f%.age}"
		done
	' sh-find {} + | wmenu -i -l 10 -p "Passage:" "$@"
)

entry=$($PASSAGE show "$name")

key=$(
	awk -F': ' '
		NR == 1 {print "Password"; next}
		/^$/ {exit}
		/^otpauth:/ {print "OTP"; next}
		{print $1}
	' <<<"$entry" | wmenu -i -l 10 -p "Passage:" "$@"
)

case $key in
"Password")
	head -n1 <<<"$entry" | tr -d '\n' | wtype -
	;;
"OTP")
	$PASSAGE otp "$name" | tr -d '\n' | wtype -
	;;
*)
	sed -n "s/^$key: //p" <<<"$entry" | tr -d '\n' | wtype -
	;;
esac
