#!/bin/bash
# Install latest development version of vsg from
# https://github.com/jeremiah-c-leary/vhdl-style-guide with uv.

yn() {
	read -p "$1 [y/N]: " -n 1 -r
	echo
	[[ $REPLY =~ ^[yY]$ ]]
}

yn "run 'uv tool install --from git+https://github.com/jeremiah-c-leary/vhdl-style-guide vsg'?" &&
	uv tool install --from git+https://github.com/jeremiah-c-leary/vhdl-style-guide vsg
