#!/bin/bash
# Install latest version of yq from
# https://github.com/mikefarah/yq.

yn() {
	read -p "$1 [y/N]: " -n 1 -r
	echo
	[[ $REPLY =~ ^[yY]$ ]]
}

yn "run 'go install github.com/mikefarah/yq/v4@latest'?" &&
	go install github.com/mikefarah/yq/v4@latest
