#!/bin/bash
set -o nounset

# Installs the latest nightly build of zig from https://ziglang.org/download to
# ~/.local without requiring root access.
#
# Note that the downloaded tar file is not removed and can be found in $TMPDIR
# or /tmp.

declare REPO=ziglang.org/download
declare NAME=zig
declare TARGETDIR="$HOME/.local"
declare OS
declare ARCH
declare TEMPDIR

die() {
	echo "${0##*/}: $1" >&2
	exit 1
}

determine_system() {
	case $(uname -s) in
	Linux*) OS=linux ;;
	Darwin*) OS=macos ;;
	*) die "unsupported os $OS" ;;
	esac

	case $(uname -m) in
	aarch64) ARCH=aarch64 ;;
	x86_64) ARCH=x86_64 ;;
	*) die "unsupported arch $ARCH" ;;
	esac
}

download() {
	url=$(curl -sSL "https://$REPO/index.json" |
		jq -r --arg arch "$ARCH" --arg os "$OS" '
			.master[$arch + "-" + $os].tarball')

	[[ -z $url ]] && die "error fetching download url"

	path=${TMPDIR:-/tmp}/${url##*/}
	curl -#Lo "$path" "$url"

	TEMPDIR=$(mktemp -d)
	trap 'rm -rf -- "$TEMPDIR"' EXIT
	tar -xf "$path" -C "$TEMPDIR"

	echo "$REPO -> $path" >&2
}

install() {
	dir=$(find "$TEMPDIR" -mindepth 1 -maxdepth 1 -type d -print -quit)

	mkdir -p "$TARGETDIR"
	rm -rf "${TARGETDIR:?}/$NAME"
	mv "$dir" "$TARGETDIR/$NAME"

	echo "$NAME/ -> $TARGETDIR/zig/" >&2
}

determine_system
download
install
