#!/bin/bash

# TODO: Until newer versions are released on a more
#       regular basis, install with Go.

yn() {
	read -p "$1 [y/N]: " -n 1 -r
	printf '\n'
	[[ $REPLY =~ ^[yY]$ ]]
}

yn "run 'go install github.com/charmbracelet/glow/v2@master'?" &&
	go install github.com/charmbracelet/glow/v2@master
