#!/bin/bash
# Install latest version of age from
# https://github.com/FiloSottile/age.

yn() {
	read -p "$1 [y/N]: " -n 1 -r
	echo
	[[ $REPLY =~ ^[yY]$ ]]
}

yn "run 'go install filippo.io/age/cmd/...@latest'?" &&
	go install filippo.io/age/cmd/...@latest
