#!/bin/bash
# Install latest version of keg from
# https://github.com/rwxrob/keg.

yn() {
	read -p "$1 [y/N]: " -n 1 -r
	echo
	[[ $REPLY =~ ^[yY]$ ]]
}

yn "run 'go install github.com/rwxrob/keg/cmd/keg@latest'?" &&
	go install github.com/rwxrob/keg/cmd/keg@latest
