#!/bin/bash
# Installs the latest release of d2 from https://github.com/terrastruct/d2 to
# ~/.local without requiring root access.
#
# Note that the downloaded tar file is not removed and can be found in $TMPDIR
# or /tmp.

set -e

declare REPO=arduino/arduino-cli
declare EXE=arduino-cli
declare TARGETDIR="$HOME/.local/bin"

declare OS
declare ARCH
declare TEMPDIR

die() {
	echo "${0##*/}: $1" >&2
	exit 1
}

determine_system() {
	case $(uname -s) in
	Linux*) OS=Linux ;;
	Darwin*) OS=macOS ;;
	*) die "unsupported os" ;;
	esac

	case $(uname -m) in
	aarch64) ARCH=ARM64 ;;
	x86_64) ARCH=64bit ;;
	*) die "unsupported architecture" ;;
	esac
}

download() {
	url=$(curl -sSL "https://api.github.com/repos/$REPO/releases/latest" |
		jq -r --arg os "$OS" --arg arch "$ARCH" '
			.assets[] |
			select(.name | contains($os) and contains($arch) and endswith(".tar.gz")) |
			.browser_download_url')

	[[ -z $url ]] && die "error fetching download url"

	path=${TMPDIR:-/tmp}/${url##*/}
	curl -#Lo "$path" "$url"

	TEMPDIR=$(mktemp -d)
	trap 'rm -rf -- "$TEMPDIR"' EXIT
	tar -xf "$path" -C "$TEMPDIR"

	echo "$REPO -> $path" >&2
}

install() {
	mkdir -p "$TARGETDIR"

	mv "$TEMPDIR/$EXE" "$TARGETDIR"
	echo "$EXE -> $TARGETDIR/$EXE" >&2
}

determine_system
download
install
