#!/bin/bash

yn() {
	read -p "$1 [y/N]: " -n 1 -r
	echo
	[[ $REPLY =~ ^[yY]$ ]]
}

echo "cargo can install a development version of typst."

yn "run 'cargo install --git https://github.com/typst/typst --locked typst-cli'?" &&
	cargo install --git https://github.com/typst/typst --locked typst-cli
