#!/bin/bash
# Install latest release of uv from https://github.com/astral-uv/uv to
# ~/.local without requiring root access.
#
# Note that the downloaded tar file is not removed and can be found in
# ~/Downloads.

set -e

declare REPO=astral-sh/uv
declare TARGETDIR="$HOME/.local/bin"
declare ARCH
declare OS
declare TEMPDIR

die() {
	echo "${0##*/}: $1" >&2
	exit 1
}

determine_system() {
	case $(uname -s) in
	Linux*) OS=unknown-linux-gnu ;;
	Darwin*) OS=apple-darwin ;;
	*) die "unsupported os" ;;
	esac

	case $(uname -m) in
	aarch64) ARCH=aarch64 ;;
	x86_64) ARCH=x86_64 ;;
	*) die "unsupported arch" ;;
	esac
}

download() {
	url=$(curl -sSL "https://api.github.com/repos/$REPO/releases/latest" |
		jq -r --arg os "$OS" --arg arch "$ARCH" '
			.assets[] |
			select(.name | contains($os) and contains($arch) and endswith(".tar.gz")) |
			.browser_download_url')

	[[ -z $url ]] && die "error fetching download url"

	path=${TMPDIR:-/tmp}/${url##*/}
	curl -#Lo "$path" "$url"

	TEMPDIR=$(mktemp -d)
	trap 'rm -rf -- "$TEMPDIR"' EXIT
	tar -xf "$path" -C "$TEMPDIR"

	echo "$REPO -> $path" >&2
}

install() {
	mkdir -p "$TARGETDIR"

	mv "$TEMPDIR/uv-$ARCH-$OS/uv" "$TARGETDIR"
	echo "uv -> $TARGETDIR/uv" >&2

	mv "$TEMPDIR/uv-$ARCH-$OS/uvx" "$TARGETDIR"
	echo "uvx -> $TARGETDIR/uvx" >&2
}

determine_system
download
install
