#!/bin/bash
# Install latest version of age-plugin-yubikey from
# https://github.com/str4d/age-plugin-yubikey.

yn() {
	read -p "$1 [y/N]: " -n 1 -r
	echo
	[[ $REPLY =~ ^[yY]$ ]]
}

yn "run
sudo dnf5 install pcsc-lite
sudo dnf5 install pcsc-lite-devel
cargo install age-plugin-yubikey
?" && {
	sudo dnf5 install pcsc-lite
	sudo dnf5 install pcsc-lite-devel
	cargo install age-plugin-yubikey
}
