#!/bin/bash
set -e

# Install latest release of Go from https://go.dev/dl to ~/.local without
# requiring root access.
#
# Note that the downloaded tar file is not removed and can be found in $TMPDIR
# or /tmp.

declare REPO=go.dev/dl
declare NAME=go
declare TARGETDIR="$HOME/.local"
declare OS
declare ARCH
declare TEMPDIR

die() {
	echo "${0##*/}: $1" >&2
	exit 1
}

determine_system() {
	case $(uname -s) in
	Linux*) OS=linux ;;
	Darwin*) OS=darwin ;;
	*) die "unsupported os" ;;
	esac

	case $(uname -m) in
	aarch64) ARCH=arm64 ;;
	x86_64) ARCH=amd64 ;;
	*) die "unsupported arch" ;;
	esac
}

download() {
	url="https://$REPO/$(curl -sSL "https://$REPO/?mode=json" |
		jq -r '.[0].files[]
			| select(.os == "'"$OS"'")
			| select(.arch == "'"$ARCH"'")
			| select(.filename | endswith(".tar.gz"))
			| .filename')"

	[[ -z $url ]] && die "error fetching download url"

	path=${TMPDIR:-/tmp}/${url##*/}
	curl -#Lo "$path" "$url"

	TEMPDIR=$(mktemp -d)
	trap 'rm -rf -- "$TEMPDIR"' EXIT
	tar -xf "$path" -C "$TEMPDIR"

	echo "$REPO -> $path" >&2
}

install() {
	mkdir -p "$TARGETDIR"
	rm -rf "${TARGETDIR:?}/$NAME"

	mv "$TEMPDIR/$NAME" "$TARGETDIR"
	echo "$NAME/ -> $TARGETDIR/$NAME/" >&2
}

determine_system
download
install
